name: Code Covering Example

on: workflow_dispatch

jobs:
  codecov:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          # Install additional python packages
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

      - name: Unit test
        run: |
          python -m pytest tests --cov codecov --cov-report=xml --color=yes
          python -m pytest --cache-clear --cov codecov tests > pytest-coverage.txt

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml

      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: pytest-coverage.txt